
set_property IOSTANDARD LVCMOS33 [get_ports {oData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[0]}]


set_property PACKAGE_PIN L18 [get_ports {oData[6]}]
set_property PACKAGE_PIN T11 [get_ports {oData[5]}]
set_property PACKAGE_PIN P15 [get_ports {oData[4]}]
set_property PACKAGE_PIN K13 [get_ports {oData[3]}]
set_property PACKAGE_PIN K16 [get_ports {oData[2]}]
set_property PACKAGE_PIN R10 [get_ports {oData[1]}]
set_property PACKAGE_PIN T10 [get_ports {oData[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property PACKAGE_PIN F4  [get_ports ps2_clk]
set_property PACKAGE_PIN B2  [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN M17 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_odata[0]}]

set_property PACKAGE_PIN V11 [get_ports {led_odata[15]}]
set_property PACKAGE_PIN V12 [get_ports {led_odata[14]}]
set_property PACKAGE_PIN V14 [get_ports {led_odata[13]}]
set_property PACKAGE_PIN V15 [get_ports {led_odata[12]}]
set_property PACKAGE_PIN T16 [get_ports {led_odata[11]}]
set_property PACKAGE_PIN U14 [get_ports {led_odata[10]}]
set_property PACKAGE_PIN T15 [get_ports {led_odata[9]}]
set_property PACKAGE_PIN V16 [get_ports {led_odata[8]}]
set_property PACKAGE_PIN U16 [get_ports {led_odata[7]}]
set_property PACKAGE_PIN U17 [get_ports {led_odata[6]}]
set_property PACKAGE_PIN V17 [get_ports {led_odata[5]}]
set_property PACKAGE_PIN R18 [get_ports {led_odata[4]}]
set_property PACKAGE_PIN N14 [get_ports {led_odata[3]}]
set_property PACKAGE_PIN J13 [get_ports {led_odata[2]}]
set_property PACKAGE_PIN K15 [get_ports {led_odata[1]}]
set_property PACKAGE_PIN H17 [get_ports {led_odata[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN J15 [get_ports enable]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enable_IBUF]


